# Generated by Django 4.1.1 on 2022-09-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='summary',
            field=models.TextField(default='since this is default u will have default'),
        ),
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
