# Generated by Django 4.1.1 on 2022-09-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_person_summary_alter_person_price_alter_person_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='summary',
            field=models.TextField(),
        ),
    ]
